"""initial

Revision ID: 68988771db5e
Revises: ab0e81c542fe
Create Date: 2025-07-21 16:36:53.570374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68988771db5e'
down_revision = 'ab0e81c542fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reminder_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('reminder_time')
        batch_op.drop_column('notes')
        batch_op.drop_column('category')
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
